### ISSUE TITLE
project structure improvements

### ISSUE THREAD

**Issue by skewballfox** [secretsauceai/precise-wakeword-model-maker#9]
I plan on working on this once I have a full successful run through, though I think documenting the extent and rationale of the changes would be valuable to make sure that they are in line with both the end goal of the project and the expectations of current users. 

## directory changes and rational:
   1. move py contents of project dir to `src/`, `src/data_prep` or `src/model_maker`
       - the reason being for this one (along with some of the filename changes) is easier navigation of source code and identification of relevant components of the application when working on a specific problem. plus it cleans up the top level directory so that stuff that the only things in it is related to the total project (the readme, the setup scripts, requirements.txt etc). 
   2. create a `tmp` directory for all by products of the process,
       - this is mainly beneficial for navigation and clearing application state: (`rm -rf project/tmp/*`), it also makes it easy for the program to clean up after itself or in the case of using the system tmp, for the system to wipe those files on reboot
   3. create an `out` dir for end result files/dirs
     - mainly to identify to the user that this is the location of the actual model has been finished and this are the desired end products of creation (don't nuke it with everything else)
   4. create a directory `test` for all testing functionality
       - because this follows standard practice there may be some tools for auto-generating some test with this. also by following practices like mirroring names with `src/whatever/file_name_test.py`, makes it easier to see what is currently being tested and what isn't.
   5. potentially create a config directory for the json files
    - if there is any configuration that is semi-permanent (for example, you want to always do this stuff, and not just per wakeword or run) then this is generally how it is handled. however compared to the above changes, this isn't too critical. 

these together also makes it easier to make rules for `.gitIgnore` that doesn't involve listing a bunch of file names that may change at some point

 ## file changes from easiest to hardest
1. change `wake_word_data_prep_ide.py` to `src/whatever/__main__.py`
    - basically signals to developers that this is the entry-point of the program and makes it easier to identify where to start when trying to follow the code execution flow.
2. change `wake_word_data_prep_classes.py` to `utility.py` or multiple `something_utils.py` 
    - signals that this is for stuff separate from the core logic of the program and primarily for the plumbing. something like `dir_util` or `fs_util` would be great as a way to signal this is where you want to look if something messes up with the creation of directories
3. add docstrings and types to all functions related to domain logic
    - this is useful if the person uses an IDE or a beefy editor like vs code because the user can see the purpose of a function by hovering over it, this makes it easier for people to debug non-logic-based issues (such as wrong param type)  with the nlp functionality without having to understand exactly what the function does. it also makes it easier for us to identify logic issues (the user used this function correctly but the end result is incorrect) and if something is incorrectly produced if one function chains multiple function together.
4. move from print to logs.
    - there are tools for making refactoring changes such as this somewhat automatically, but this has multiple benefits such as filtering output and identifying issues if the root cause is too high up for the terminal to scroll to. however this will still be more involved than the above changes, so we will probably save this one for later.

the majority of these are fairly low-hanging fruit that makes it easier for people to get up and running, both in using the code and contributing back to the end project.

**Comment by skewballfox** [comment]
as an addedum I'm thinking we should split `wake_word_data_prep_classes.py` into 3 files: `dir_util.py/fs_util.py`, `model_utils.py`,`precise_utils.py` 

the reason I think model utilities should be separate from precise utilities is mainly to keep all the stuff that won't change if we move to another precise engine in model utils, and try to separate most of the logic related to handling the precise engine itself from the rest of the codebase. 

This makes it easy to migrate and even to do things like benchmark multiple versions of the engines side by side

**Comment by AmateurAcademic** [comment]
Sounds good. I would like to finish testing and push my new model analytics features that I have worked on before doing this. But otherwise this all sounds great! Thanks for the input! :)

**Comment by secretsauceai** [comment]
@skewballfox would you consider this refactoring done?

**Comment by skewballfox** [comment]
to an extent yes, just having a single out directory is fine so long as the program cleans up the temporary stuff itself. 

We still need to programmatically put stuff in the out directory, but that is mainly to make it harder to mess up pathing, and easier to fix in one spot(hence I've wanted to add a model class that provides methods for accessing or modifying the contents of it's directories). that isn't exactly a low hanging fruit though, and should probably be addressed by a separate issue.

we have the test directory from the original mycroft precise, but haven't yet started adding test for data prep. that will probably only matter further down the road though.

we do need to add docstrings to a lot of the code, documenting stuff like input and output, the purpose of certain files or functions, etc. Especially the nlp stuff where contributers may not have built up their vocabulary (but can still tell from the input and output that something got passed wrong, for example)

because this is mainly meant to be a infrequently used commandline tool(I doubt many people will be headlessly creating wakewords multiple times a day), print to logs only matters if we are dealing with an issue where something went wrong much earlier in execution, but didn't cause a failure until a certain length of time afterwards(where scrolling up to the source of the issue is impossible). so that is more take it or leave it depending on how likely you expect such an event to be.

**Comment by skewballfox** [comment]
closing this as I opened issue for the two more important project improvements that still need to be implemented.
